set(BUILD_VERSION_HEADER_FILE "${CMAKE_CURRENT_LIST_DIR}/Source/BuildVersion.hpp")
set(BUILD_VERSION_CACHE_FILE "${CMAKE_CURRENT_LIST_DIR}/build_number")

IF(EXISTS ${BUILD_VERSION_CACHE_FILE})
    file(READ ${BUILD_VERSION_CACHE_FILE} INCREMENTED_VALUE)
    math(EXPR INCREMENTED_VALUE "${INCREMENTED_VALUE}+1")
ELSE()
    set(INCREMENTED_VALUE "1")
ENDIF()

execute_process(
    COMMAND  git rev-parse --short HEAD
    OUTPUT_VARIABLE GIT_HASH
)
string(REPLACE "\n" "" GIT_HASH ${GIT_HASH})

file(WRITE ${BUILD_VERSION_CACHE_FILE} "${INCREMENTED_VALUE}")

file(WRITE ${BUILD_VERSION_HEADER_FILE}
    "#pragma once\
    \n\nstatic const unsigned int BUILD_VERSION = ${INCREMENTED_VALUE};\
    \nstatic const unsigned int GIT_HASH_SHORT = 0x${GIT_HASH};\n"
)
