name: Build (Windows)

on:
  push:
    branches: [ Develop ]
    paths:
      - '.github/workflows/build_windows.yml'
      - 'Source/**'
      - '!Source/Doxyfile'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Setup Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.0.2
      
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install VMA submodule
        uses: actions/checkout@v2
        with:
          repository: GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator
          path: ThirdParty/VulkanMemoryAllocator
          
      - name: Build
        shell: pwsh        
        run:  |
          cmake . -Bbuild -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 16 2019" -A x64
          cmake --build build --config Release
          
