name: Build (Ubuntu 20.04)

on:
  push:
    branches: [ Develop ]
  pull_request:
    branches: [ Develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:20.04
    env:
      DEBIAN_FRONTEND: "noninteractive"
    steps:
      - uses: actions/checkout@v2

      - name: Install git submodules
        shell: bash
        run: |
          git submodule update --init --recursive

      - name: Install dependecies
        shell: bash
        run: |
          apt update && apt install -y sudo
          apt install -y \
            g++-10 \
            wget \
            gnupg2 \
            clang \
            cmake \
            curl \
            libgl1-mesa-dev \
            libx11-dev \
            libx11-xcb-dev \
            libxcb-icccm4-dev \
            libxcb-image0-dev \
            libxcb-keysyms1-dev \
            libxcb-randr0-dev \
            libxcb-render-util0-dev \
            libxcb-render0-dev \
            libxcb-shape0-dev \
            libxcb-sync-dev \
            libxcb-xfixes0-dev \
            libxcb-xinerama0-dev \
            libxcb-xkb-dev \
            libgtest-dev \
            xorg-dev

      - name: Install Vulkan
        shell: bash
        run: |
          wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
          wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.2.154-focal.list https://packages.lunarg.com/vulkan/1.2.154/lunarg-vulkan-1.2.154-focal.list
          apt update && apt install -y vulkan-sdk

      - name: Configure CMake
        shell: bash
        run: |
            export PATH=$VULKAN_SDK/bin:$PATH
            export LD_LIBRARY_PATH=$VULKAN_SDK/lib:$LD_LIBRARY_PATH
            export VK_LAYER_PATH=$VULKAN_SDK/etc/explicit_layer.d

      - name: CMake
        run: cmake -Bbuild -D CMAKE_CXX_COMPILER=g++-10
      - name: Build
        run: cmake --build build


