name: C/C++ CI

on:
  push:
    branches: [ Develop ]
  pull_request:
    branches: [ Develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      # dependencies
    - name: vulkan 
      run: sudo apt install libvulkan1 mesa-vulkan-drivers vulkan-utils
    - name: gtests
      run: sudo apt install libgtest-dev
    - name: cmake
      run: cmake .
    - name: make
      run: make
      # run tests
    - name: run
      run: Tests/Tests
