name: Tests

on:
  push:
    branches: [ Develop ]
    paths:
      - '.github/workflows/tests.yml'
      - 'Shaders/**'
      - 'Source/**'
      - 'Tests/**'

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    env:
      DEBIAN_FRONTEND: "noninteractive"
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            os: "ubuntu-latest",
            build_type: "Debug",            
          }
          - {
            os: "ubuntu-latest",
            build_type: "Release",            
          }
          - {
            os: "windows-latest",
            build_type: "Debug",            
          }
          - {
            os: "windows-latest",
            build_type: "Release",            
          }
    steps:
      - uses: actions/checkout@v2
      
      - name: install GoogleTest
        run: |
          cd ..
          git clone https://github.com/google/googletest.git --branch release-1.11.0
          cd googletest
          cmake -Bbuild -DCMAKE_INSTALL_PREFIX="$HOME/googletest/" -Dgtest_force_shared_crt=1
          cmake --build build --config ${{ matrix.config.build_type }}
          cmake --build build --target install --config ${{ matrix.config.build_type }}          
                
      - name: CMake config
        env:
          GTEST_ROOT: "$HOME/googletest"
        run: |
          cd Tests
          cmake -Bbuild -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} -Dgtest_force_shared_crt=ON

      - name: Build
        run: |
          cd Tests
          cmake --build build --config ${{ matrix.config.build_type }}
        
      - name: Run
        run: |
          cd Tests/build
          ctest